### ISSUE TITLE
bug: Release at a detached commit

### ISSUE THREAD

**Issue by cutecutecat** [tensorchord/envd-lsp#21]
## Description
Release tag push at a detached commit of a fork of `depandabot`.

Which lead to `v0.2.4` as the only available last tag and changelog contains whole history.

## Example:
![image](https://user-images.githubusercontent.com/19801166/210691006-1851c6a1-5959-4f91-81e2-87fc42ec5eec.png)

![image](https://user-images.githubusercontent.com/19801166/210475232-79c73f68-649b-4241-abd9-874da4b965d8.png)

detached commit: https://github.com/tensorchord/envd-lsp/commit/9bb022fd9674a11aaa535eff9791246b185ae543

## Reproduction

```shell
git tag
v0.0.1-alpha.1
v0.0.1-alpha.2
v0.0.1-alpha.3
v0.2.0
v0.2.2
v0.2.3
v0.2.4
v0.2.5
v0.3.0
v0.3.1
v0.3.5

git describe --abbrev=0 --tags
v0.2.4
```

## Additional Info
Action: https://github.com/tensorchord/envd-lsp/actions/runs/3828232773/jobs/6513594739
The Action checkout the detached branch.

![image](https://user-images.githubusercontent.com/19801166/210475676-29ddee42-33be-41e9-bf32-e99a1babdba1.png)

## Fix
To fix it, we need to:
- Remove `mathieudutour/github-tag-action@v6.1` and turn to `git tag push`
- Add `ref: main` to `actions/checkout@v3` to force pull main branch
- Add `kachick/wait-other-jobs@v1` to wait PR merged finished before push tag

```
- name: Wait other jobs(CI and lint)
      uses: kachick/wait-other-jobs@v1
      timeout-minutes: 10
      with:
        min-interval-seconds: '10'
        github-token: '${{ secrets.GITHUB_TOKEN }}'
```
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
