### ISSUE TITLE
bug: Dangerous access control

### ISSUE THREAD

**Issue by cutecutecat** [tensorchord/envd-lsp#9]
## Description
```yaml
name: release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    paths:
    - '.github/workflows/release.yml'
    - '.goreleaser.yaml'
```

It will trigerr release when a **PR created**, not PR merged. A hacker can produce a bad PR, and easily ruin the newest release.

ref: https://github.com/orgs/community/discussions/26724

As PR merge always triger a push, we can use:
```yaml
name: release

on:
  push:
    tags:
      - 'v*'
    paths:
    - '.github/workflows/release.yml'
    - '.goreleaser.yaml'
```
instead. ref: https://github.com/orgs/community/discussions/26273

## Reproduction
Create a PR of `.github/workflows/release.yml` changed.

Demo: https://github.com/cutecutecat/envd-lsp/pull/1
The release is actually trigererd!

## Additional Info

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by VoVAllen** [comment]
I think PR cannot access the repo's secret. Only merged pr can access the repo's secret

**Comment by VoVAllen** [comment]
So user can waste the computing resources, but won't have access to the secrets

**Comment by cutecutecat** [comment]
> I think PR cannot access the repo's secret. Only merged pr can access the repo's secret

Yes, you are right, sorry about that I am not familiar with Github secret. 

But it might be better if I make a patch here. Apart from computing resources, it will make contributor happy if all the CI/CD passed.

**Comment by cutecutecat** [comment]
```
name: release

on:
  push:
    tags:
      - 'v*'
    paths:
    - '.github/workflows/release.yml'
    - '.goreleaser.yaml'
```
not works as the default condition is `and` not `or`.

```
on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
```

works bad with `tag` also due to conditional `or`.

Leaving it as it is is probably the best thing to do.
